### ISSUE TITLE
FE US4: Create a "Feed" page with all available job posts, enable user to click help

### ISSUE THREAD

**Issue by sinakle** [sopra-fs24-group-19/client-group19#4]

**Comment by nina22221111** [comment]
Home Feed without styling: b88815c97f1c48e27f3b00bb830539ddc9cf5324

Added first changes to styling: a7570195825936c2537cc41e0706d0ce5e3cd347

Fixed header h2: 76155b019aec3899af83646845f253b25bf303d9

Fixed styling: a599143d209980384c0edaea703188576994c517

Added help button, still no functionality: c68c02a9a84ee30f4aabdb415d8f56afdbea3408

Added Help button and handleHelpClick function to HomeFeed: 572994992a3de15af9e5a9cd0fe7f76cf0fb6954
