### ISSUE TITLE
FE US1: Set up environment for frontend

### ISSUE THREAD

**Issue by sinakle** [sopra-fs24-group-19/client-group19#8]

**Comment by sinakle** [comment]
Find an appropriate template and set up classes etc.

**Comment by nina22221111** [comment]
Added placeholders for most of the pages, as well as their guards: afe7511d42985d8e70a63abf1cd6fc737e10eb18

initial header: 23141099c02fea53bcbfa8b509c5497b031052fd

Added Header component to other pages: 0f10c6dbd57db1ed491cf95289580d56a85b37af

Updated routing and views: 26ea98296ee9722e449d7c82bd843fbb9fd8cce6

Colors: dcd69cf9f4540f1467c7ca53da8ccd515a975c85

Updated Header styles and added NavBar component: bbd40c1f597f9bd0377d395a752ac54ff6950461

Colors: 337ea27c7820bdb2f314df9700455d8be0d45b90
